# 1)Create a 3*3*3 array with random values

In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.1726313  0.31160256 0.59977904]
  [0.15614859 0.17113507 0.40788628]
  [0.20015593 0.20800003 0.34096479]]

 [[0.16729976 0.55847939 0.08300995]
  [0.57642959 0.93732709 0.34184778]
  [0.30019135 0.30009854 0.43413646]]

 [[0.23680598 0.72145404 0.18115935]
  [0.73044262 0.04057577 0.94658704]
  [0.45318226 0.74117843 0.03068014]]]


# 2)Create a 5*5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np

# Create a 5x5 matrix with zeros
matrix = np.zeros((5, 5))

# Set values 2, 3, and 4 just below the diagonal
np.fill_diagonal(matrix[1:], 2)
np.fill_diagonal(matrix[2:], 3)
np.fill_diagonal(matrix[3:], 4)

print(matrix)

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [3. 2. 0. 0. 0.]
 [4. 3. 2. 0. 0.]
 [0. 4. 3. 2. 0.]]


# 3)Create a 8*8 matrix and fill it with a checkboard pattern

In [4]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with the checkerboard pattern
matrix[1::2, ::2] = 1  # Rows 2, 4, 6 (indexing starts from 0) and alternate columns
matrix[::2, 1::2] = 1  # Rows 1, 3, 5 and alternate columns

# Print the checkerboard pattern
for row in matrix:
    print(" ".join(map(str, row)))

0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0


# 4)Normalize a 5*5 random matrix

In [6]:
import numpy as np

# Create a random 5x5 matrix
matrix = np.random.rand(5, 5)

# Calculate the minimum and maximum values in the matrix
min_value = np.min(matrix)
max_value = np.max(matrix)

# Normalize the matrix to range [0, 1]
normalized_matrix = (matrix - min_value) / (max_value - min_value)

# Print the original and normalized matrices
print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.50604556 0.56286318 0.74091019 0.15344566 0.17697355]
 [0.55373054 0.39228044 0.87385438 0.08008815 0.79664548]
 [0.51747875 0.02252419 0.92161128 0.20128518 0.98813631]
 [0.27676226 0.80265948 0.36527241 0.97545347 0.49122637]
 [0.69137485 0.05284912 0.79980014 0.40732532 0.32774407]]

Normalized Matrix:
[[0.50074078 0.55958183 0.74396954 0.13558391 0.15994969]
 [0.55012395 0.3829242  0.8816482  0.05961396 0.8016897 ]
 [0.51258114 0.         0.93110585 0.18512712 1.        ]
 [0.26329212 0.80791788 0.35495435 0.9868655  0.48539385]
 [0.69267012 0.03140488 0.80495671 0.39850487 0.31608953]]


# 5)How to find common values between two arrays.

In [7]:
import numpy as np

def find_common_elements(arr1, arr2):
    common_elements = np.intersect1d(arr1, arr2)
    return common_elements

# Example usage:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
result = find_common_elements(array1, array2)
print(result) 

[3 4 5]


# 6)Write a python code how to get the dates of yesterday, today,and tomorrow

In [22]:
import numpy as np
import datetime

# Get the current date
today = np.datetime64('today')

# Calculate yesterday and tomorrow
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

# Convert the numpy.datetime64 objects to Python datetime objects for better readability (optional)
today = today.astype(datetime.datetime)
yesterday = yesterday.astype(datetime.datetime)
tomorrow = tomorrow.astype(datetime.datetime)

# Print the results
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


In [ ]:
#7)Consider two random arraysA

In [9]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([1, 2, 3, 4, 5])

# Check if the arrays are equal
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are equal.


# 8)Create random vector of size 10 and replace the maximum value by 0

In [10]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original vector:")
print(random_vector)

Original vector:
[0.82616287 0.30828939 0.         0.31758905 0.35735086 0.45790246
 0.33185355 0.46789253 0.70578581 0.00926165]


# 9)Write a python code how to print all the values of an array

In [11]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Print all the values in the array
for value in my_array:
    print(value)

1
2
3
4
5


# 10)Subtract the mean of each row of a matrix

In [12]:
import numpy as np

# Sample matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
result_matrix = matrix - row_means.reshape(-1, 1)

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(result_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11)Consider a given vector, how to add 1 to each element indexed  by a second vector(be careful with repeated indices)

In [13]:
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector with indices
indices_vector = np.array([1, 3, 2, 1, 4, 0])

# Create a dictionary to store the indices and their counts
index_counts = {}
for index in indices_vector:
    if index in index_counts:
        index_counts[index] += 1
    else:
        index_counts[index] = 1

# Add 1 to each element indexed by the second vector (taking care of repeated indices)
result_vector = given_vector.copy()
for index, count in index_counts.items():
    result_vector[index] += count

print(result_vector)

[2 4 4 5 6]


# 12)How to get the diagonal of a dot product

In [23]:
import numpy as np

# Create two example matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of A and B
C = np.dot(A, B)

# Extract the diagonal elements of C
diagonal = np.diag(C)

print("Matrix C:")
print(C)

print("Diagonal of C:")
print(diagonal)

Matrix C:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Diagonal of C:
[30 69 90]


# 13)How to find the most frequent value in an array

In [25]:
def most_frequent_value(arr):
    # Create an empty dictionary to store the frequency of each value
    frequency_dict = {}
    
    # Iterate through the array and update the frequency dictionary
    for value in arr:
        if value in frequency_dict:
            frequency_dict[value] += 1
        else:
            frequency_dict[value] = 1
    
    # Find the maximum frequency and corresponding value
    max_frequency = 0
    most_frequent = None
    for value, frequency in frequency_dict.items():
        if frequency > max_frequency:
            max_frequency = frequency
            most_frequent = value
    
    return most_frequent

# Example usage:
arr = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
result = most_frequent_value(arr)
print("The most frequent value is:", result)

The most frequent value is: 4


# 14)how to get the n largest values of an array

In [16]:
import numpy as np

# Sample array
arr = np.array([12, 45, 23, 6, 78, 91, 32, 55, 8, 19])

# Number of largest values you want to find
n = 3

# Use numpy.partition to get the n largest values
largest_values = np.partition(arr, -n)[-n:]

print("Array:", arr)
print(f"The {n} largest values are:", largest_values)

Array: [12 45 23  6 78 91 32 55  8 19]
The 3 largest values are: [55 78 91]


# 15)how to create a record array from regular array

In [18]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Hema', 25),
                          (2, 'Navii', 30),
                          (3, 'Lucky', 22)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Create a record array from the regular array
record_array = regular_array.view(np.recarray)

# Accessing elements in the record array
print("ID:", record_array.id)
print("Name:", record_array.name)
print("Age:", record_array.age)

ID: [1 2 3]
Name: ['Hema' 'Navii' 'Lucky']
Age: [25 30 22]


# 16)how to swap two rows of an array

In [20]:
import numpy as np

# Create a sample 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the row numbers you want to swap
row1 = 0  # Row 1 (0-based index)
row2 = 2  # Row 2 (0-based index)

# Swap the rows
array[row1], array[row2] = array[row2].copy(), array[row1].copy()

# Print the modified array
print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17)Write python code to reshape to the next dimension of numpy array

In [21]:
import numpy as np

# Create a sample NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6])  # 1-D array with 6 elements

# Determine the new shape by increasing the dimension by 1
new_shape = (original_array.size, 1)

# Reshape the array to the next dimension
reshaped_array = original_array.reshape(new_shape)

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
